baseURL: 'http://m.hqapps.tk/'
languageCode: 'en-us'
title: 'HQ Apps'

theme: "hq-store-hugo-theme"

markup:
  goldmark:
    renderer:
      unsafe: false

taxonomies:
 - tag: ["Cummunication", "Efficeny"]

outputs:
  page: ["html", "json"]
  section: ["html", "json"]
  home: ["html", "json"]

menu:
  nav:
  - identifier: featured
    name: Featured
    title: Featured
    pageref: /
  - identifier: apps
    name: All
    title: All Apps
    url: /apps
  - Identifier: update
    name: Updatz!
    title: Updatz!
    pageref: /update
