baseURL: 'http://m.hqapps.tk/'
languageCode: 'en-us'
title: 'HQ Apps'

theme: "store"

markup:
  goldmark:
    renderer:
      unsafe: false

menu:
  bottom:
  - identifier: apps
    name: Epps
    title: HQ APPS APPS
    url: /apps/
  - identifier: games
    name: Gamz!
    title: gaymes
    url: /games/
  - identifier: update
    name: Updatz!
    title: Updatz!
    url: /update/
  - identifier: settings
    name: Setting
    title: Setting
    url: /settings/
